package ejulp.Vistas;

import ejulp.AccesoAdatos.AlumnoData;
import javax.swing.JTextField;
import ejulp.Entidades.Alumno;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class formAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioAlumno
     */
    public formAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modificar_datos = new javax.swing.JButton();
        eliminar_alumno = new javax.swing.JButton();
        guardar_AlumnoNuevo = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        textField_BusquedaDni = new javax.swing.JTextField();
        boton_BuscarDni = new javax.swing.JButton();
        textField_apellido = new javax.swing.JTextField();
        textField_nombre = new javax.swing.JTextField();
        datechooser_fechanacimiento = new com.toedter.calendar.JDateChooser();
        checkbox_activo = new javax.swing.JCheckBox();
        limpiar_campos = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 0, 255));
        setForeground(java.awt.Color.white);
        setTitle("Alumnos");
        setToolTipText("");

        jDesktopPane1.setForeground(new java.awt.Color(51, 0, 255));

        jLabel1.setText("Documento");

        jLabel2.setText("Apeliido");

        jLabel3.setText("Nombre");

        jLabel4.setText("Estado");

        jLabel5.setText("Fecha de Nacimiento");

        modificar_datos.setText("Modificar Datos");
        modificar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_datosActionPerformed(evt);
            }
        });

        eliminar_alumno.setText("Eliminar Alumno");
        eliminar_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_alumnoActionPerformed(evt);
            }
        });

        guardar_AlumnoNuevo.setText("Guardar Alumno");
        guardar_AlumnoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_AlumnoNuevoActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
=======
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
>>>>>>> main
            }
        });

        textField_BusquedaDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_BusquedaDniActionPerformed(evt);
            }
        });

        boton_BuscarDni.setText("Buscar");
        boton_BuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BuscarDniActionPerformed(evt);
            }
        });

        textField_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_apellidoActionPerformed(evt);
            }
        });

        textField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_nombreActionPerformed(evt);
            }
        });

        datechooser_fechanacimiento.setDateFormatString("yyyy-MM-dd");
        datechooser_fechanacimiento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datechooser_fechanacimientoPropertyChange(evt);
            }
        });

        checkbox_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_activoActionPerformed(evt);
            }
        });

        limpiar_campos.setText("Limpiar Campos");
        limpiar_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_camposActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(modificar_datos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(eliminar_alumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(guardar_AlumnoNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(salir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textField_BusquedaDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(boton_BuscarDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textField_apellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(textField_nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(datechooser_fechanacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(checkbox_activo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(limpiar_campos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datechooser_fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addComponent(checkbox_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textField_BusquedaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(modificar_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminar_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_BuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardar_AlumnoNuevo))
                        .addGap(52, 52, 52))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(limpiar_campos)
                .addGap(31, 31, 31)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textField_BusquedaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_BuscarDni))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textField_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkbox_activo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(datechooser_fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar_datos)
                    .addComponent(eliminar_alumno)
                    .addComponent(guardar_AlumnoNuevo))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiar_campos)
                    .addComponent(salir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    AlumnoData vista_FormAlumno = new AlumnoData();

    private void boton_BuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BuscarDniActionPerformed

        try {

            String busqueda_dni = textField_BusquedaDni.getText();

            int dni = Integer.parseInt(busqueda_dni);

            Alumno recuperado_bydni = vista_FormAlumno.buscarAlumnoDni(dni);

            textField_apellido.setText(recuperado_bydni.getApellido());
            textField_nombre.setText(recuperado_bydni.getNombre());
            checkbox_activo.setSelected(recuperado_bydni.isActivo());
            datechooser_fechanacimiento.setDate(Date.from(recuperado_bydni.getFechaNac().atStartOfDay(ZoneId.systemDefault()).toInstant()));

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Formato de DNI incorrecto.");

        }


    }//GEN-LAST:event_boton_BuscarDniActionPerformed

    private void textField_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_apellidoActionPerformed

    }//GEN-LAST:event_textField_apellidoActionPerformed

    private void textField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_nombreActionPerformed


    }//GEN-LAST:event_textField_nombreActionPerformed

    private void checkbox_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_activoActionPerformed


    }//GEN-LAST:event_checkbox_activoActionPerformed

    private void textField_BusquedaDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_BusquedaDniActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_textField_BusquedaDniActionPerformed


    private void datechooser_fechanacimientoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datechooser_fechanacimientoPropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_datechooser_fechanacimientoPropertyChange

    private void guardar_AlumnoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_AlumnoNuevoActionPerformed

        try {
            int dni = Integer.parseInt(textField_BusquedaDni.getText());
            String apellido = textField_apellido.getText();
            String nombre = textField_nombre.getText();
            boolean estado = checkbox_activo.isSelected();
            String fecha = ((JTextField) datechooser_fechanacimiento.getDateEditor().getUiComponent()).getText();

            // Verificar si el alumno ya existe en la base de datos
            if (vista_FormAlumno.existeAlumno(dni)) {
                JOptionPane.showMessageDialog(null, "El alumno ya existe en la base de datos.");
            } else {
                // Si el alumno no existe, guardarlo en la base de datos
                Alumno guardar_NuevoAlumno = new Alumno(dni, apellido, nombre, LocalDate.parse(fecha), estado);
                vista_FormAlumno.guardarAlumno(guardar_NuevoAlumno);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Formato de DNI incorrecto.");
        }

    }//GEN-LAST:event_guardar_AlumnoNuevoActionPerformed

    private void eliminar_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_alumnoActionPerformed

        vista_FormAlumno.eliminarAlumno(vista_FormAlumno.buscarAlumnoDni(Integer.parseInt(textField_BusquedaDni.getText())).getIdAlumno());


    }//GEN-LAST:event_eliminar_alumnoActionPerformed

    private void limpiar_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_camposActionPerformed

        textField_BusquedaDni.setText("");
        textField_apellido.setText("");
        textField_nombre.setText("");
        checkbox_activo.setSelected(false);
        datechooser_fechanacimiento.setDate(null);

    }//GEN-LAST:event_limpiar_camposActionPerformed

    private void modificar_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_datosActionPerformed

        int dni = Integer.parseInt(textField_BusquedaDni.getText());
        String apellido = textField_apellido.getText();
        String nombre = textField_nombre.getText();
        boolean estado = checkbox_activo.isSelected();
        String fecha = ((JTextField) datechooser_fechanacimiento.getDateEditor().getUiComponent()).getText();

        Alumno modificar_alumno = new Alumno(dni, apellido, nombre, LocalDate.parse(fecha), estado);

        vista_FormAlumno.modificarAlumno(modificar_alumno);

    }//GEN-LAST:event_modificar_datosActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_BuscarDni;
    private javax.swing.JCheckBox checkbox_activo;
    private com.toedter.calendar.JDateChooser datechooser_fechanacimiento;
    private javax.swing.JButton eliminar_alumno;
    private javax.swing.JButton guardar_AlumnoNuevo;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton limpiar_campos;
    private javax.swing.JButton modificar_datos;
    private javax.swing.JButton salir;
    private javax.swing.JTextField textField_BusquedaDni;
    private javax.swing.JTextField textField_apellido;
    private javax.swing.JTextField textField_nombre;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(JTextField textField_BusquedaDni) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
